"""add source_services to track_plays

Revision ID: 040d47093f7d
Revises: 0d4a116d16b1
Create Date: 2026-03-12 00:06:50.373650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040d47093f7d'
down_revision: Union[str, None] = '0d4a116d16b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_services', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_plays', schema=None) as batch_op:
        batch_op.drop_column('source_services')

    # ### end Alembic commands ###
