"""add match_reviews table

Revision ID: 0d4a116d16b1
Revises: 904c29981ae8
Create Date: 2026-03-11 01:17:19.830521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4a116d16b1'
down_revision: Union[str, None] = '904c29981ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('connector_name', sa.String(length=32), nullable=False),
    sa.Column('connector_track_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('match_weight', sa.Float(), nullable=False),
    sa.Column('confidence_evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_track_id'], ['connector_tracks.id'], name=op.f('fk_match_reviews_connector_track_id_connector_tracks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_match_reviews_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_reviews')),
    sa.UniqueConstraint('track_id', 'connector_name', 'connector_track_id', name='uq_match_reviews_track_connector')
    )
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_match_reviews_status', ['status'], unique=False)
        batch_op.create_index('ix_match_reviews_track_id', ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_match_reviews_track_id')
        batch_op.drop_index('ix_match_reviews_status')

    op.drop_table('match_reviews')
    # ### end Alembic commands ###
