"""initial_hard_delete_schema

Revision ID: 3c3c6f0ed187
Revises:
Create Date: 2025-08-16 23:58:40.716434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c3c6f0ed187"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_playlists",
        sa.Column("connector_name", sa.String(), nullable=False),
        sa.Column("connector_playlist_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("owner_id", sa.String(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("collaborative", sa.Boolean(), nullable=False),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_playlists")),
        sa.UniqueConstraint(
            "connector_name",
            "connector_playlist_id",
            name=op.f("uq_connector_playlists_connector_playlists_connector_name"),
        ),
    )
    op.create_table(
        "connector_tracks",
        sa.Column("connector_name", sa.String(length=32), nullable=False),
        sa.Column("connector_track_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artists", sa.JSON(), nullable=False),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("isrc", sa.String(length=32), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=True),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_tracks")),
        sa.UniqueConstraint(
            "connector_name",
            "connector_track_id",
            name=op.f("uq_connector_tracks_connector_tracks_connector_name"),
        ),
    )
    with op.batch_alter_table("connector_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_connector_tracks_connector_name"),
            ["connector_name", "isrc"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_connector_tracks_isrc"), ["isrc"], unique=False
        )

    op.create_table(
        "playlists",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("track_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlists")),
    )
    op.create_table(
        "sync_checkpoints",
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("last_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_checkpoints")),
        sa.UniqueConstraint(
            "user_id",
            "service",
            "entity_type",
            name=op.f("uq_sync_checkpoints_sync_checkpoints_user_id"),
        ),
    )
    op.create_table(
        "tracks",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("artists", sa.JSON(), nullable=False),
        sa.Column("album", sa.String(length=255), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("release_date", sa.DateTime(), nullable=True),
        sa.Column("isrc", sa.String(length=32), nullable=True),
        sa.Column("spotify_id", sa.String(length=64), nullable=True),
        sa.Column("mbid", sa.String(length=36), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracks")),
        sa.UniqueConstraint("isrc", name="uq_tracks_isrc"),
        sa.UniqueConstraint("mbid", name="uq_tracks_mbid"),
        sa.UniqueConstraint("spotify_id", name="uq_tracks_spotify_id"),
    )
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracks_isrc"), ["isrc"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracks_mbid"), ["mbid"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracks_spotify_id"), ["spotify_id"], unique=False
        )
        batch_op.create_index("ix_tracks_title", ["title"], unique=False)

    op.create_table(
        "playlist_mappings",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("connector_name", sa.String(length=32), nullable=False),
        sa.Column("connector_playlist_id", sa.String(length=64), nullable=False),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name=op.f("fk_playlist_mappings_playlist_id_playlists"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_mappings")),
        sa.UniqueConstraint(
            "connector_name", "connector_playlist_id", name="uq_connector_playlist"
        ),
        sa.UniqueConstraint(
            "playlist_id", "connector_name", name="uq_playlist_connector"
        ),
    )
    op.create_table(
        "playlist_tracks",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("sort_key", sa.String(length=32), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name=op.f("fk_playlist_tracks_playlist_id_playlists"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_playlist_tracks_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_playlist_tracks")),
    )
    with op.batch_alter_table("playlist_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playlist_tracks_playlist_id"),
            ["playlist_id", "sort_key"],
            unique=False,
        )

    op.create_table(
        "track_likes",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("is_liked", sa.Boolean(), nullable=False),
        sa.Column("liked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_synced", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_track_likes_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_likes")),
        sa.UniqueConstraint(
            "track_id", "service", name=op.f("uq_track_likes_track_likes_track_id")
        ),
    )
    with op.batch_alter_table("track_likes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_likes_service"), ["service", "is_liked"], unique=False
        )

    op.create_table(
        "track_mappings",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("connector_track_id", sa.Integer(), nullable=False),
        sa.Column("connector_name", sa.String(length=32), nullable=False),
        sa.Column("match_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("confidence_evidence", sa.JSON(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_track_id"],
            ["connector_tracks.id"],
            name=op.f("fk_track_mappings_connector_track_id_connector_tracks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_track_mappings_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_mappings")),
        sa.UniqueConstraint(
            "connector_track_id",
            "connector_name",
            name="uq_connector_track_canonical_mapping",
        ),
    )
    with op.batch_alter_table("track_mappings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_track_mappings_connector_lookup", ["connector_track_id"], unique=False
        )
        batch_op.create_index(
            "ix_track_mappings_connector_name", ["connector_name"], unique=False
        )
        batch_op.create_index(
            "ix_track_mappings_track_lookup", ["track_id"], unique=False
        )
        batch_op.create_index(
            "uq_primary_mapping",
            ["track_id", "connector_name"],
            unique=True,
            sqlite_where=sa.text("is_primary = TRUE"),
        )

    op.create_table(
        "track_metrics",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("connector_name", sa.String(length=32), nullable=False),
        sa.Column("metric_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_track_metrics_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_metrics")),
        sa.UniqueConstraint(
            "track_id",
            "connector_name",
            "metric_type",
            name=op.f("uq_track_metrics_track_metrics_track_id"),
        ),
    )
    with op.batch_alter_table("track_metrics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_track_metrics_track_id"),
            ["track_id", "connector_name", "metric_type"],
            unique=False,
        )

    op.create_table(
        "track_plays",
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=32), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ms_played", sa.Integer(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("import_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_source", sa.String(length=32), nullable=True),
        sa.Column("import_batch_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("fk_track_plays_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_track_plays")),
        sa.UniqueConstraint(
            "track_id",
            "service",
            "played_at",
            "ms_played",
            name="uq_track_plays_deduplication",
        ),
    )
    with op.batch_alter_table("track_plays", schema=None) as batch_op:
        batch_op.create_index(
            "ix_track_plays_import_batch", ["import_batch_id"], unique=False
        )
        batch_op.create_index(
            "ix_track_plays_import_source", ["import_source"], unique=False
        )
        batch_op.create_index("ix_track_plays_played_at", ["played_at"], unique=False)
        batch_op.create_index("ix_track_plays_service", ["service"], unique=False)
        batch_op.create_index("ix_track_plays_track_id", ["track_id"], unique=False)
        batch_op.create_index(
            "ix_track_plays_track_played", ["track_id", "played_at"], unique=False
        )
        batch_op.create_index(
            "ix_track_plays_track_service", ["track_id", "service"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_plays", schema=None) as batch_op:
        batch_op.drop_index("ix_track_plays_track_service")
        batch_op.drop_index("ix_track_plays_track_played")
        batch_op.drop_index("ix_track_plays_track_id")
        batch_op.drop_index("ix_track_plays_service")
        batch_op.drop_index("ix_track_plays_played_at")
        batch_op.drop_index("ix_track_plays_import_source")
        batch_op.drop_index("ix_track_plays_import_batch")

    op.drop_table("track_plays")
    with op.batch_alter_table("track_metrics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_metrics_track_id"))

    op.drop_table("track_metrics")
    with op.batch_alter_table("track_mappings", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_primary_mapping", sqlite_where=sa.text("is_primary = TRUE")
        )
        batch_op.drop_index("ix_track_mappings_track_lookup")
        batch_op.drop_index("ix_track_mappings_connector_name")
        batch_op.drop_index("ix_track_mappings_connector_lookup")

    op.drop_table("track_mappings")
    with op.batch_alter_table("track_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_track_likes_service"))

    op.drop_table("track_likes")
    with op.batch_alter_table("playlist_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playlist_tracks_playlist_id"))

    op.drop_table("playlist_tracks")
    op.drop_table("playlist_mappings")
    with op.batch_alter_table("tracks", schema=None) as batch_op:
        batch_op.drop_index("ix_tracks_title")
        batch_op.drop_index(batch_op.f("ix_tracks_spotify_id"))
        batch_op.drop_index(batch_op.f("ix_tracks_mbid"))
        batch_op.drop_index(batch_op.f("ix_tracks_isrc"))

    op.drop_table("tracks")
    op.drop_table("sync_checkpoints")
    op.drop_table("playlists")
    with op.batch_alter_table("connector_tracks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connector_tracks_isrc"))
        batch_op.drop_index(batch_op.f("ix_connector_tracks_connector_name"))

    op.drop_table("connector_tracks")
    op.drop_table("connector_playlists")
    # ### end Alembic commands ###
