"""add sync management columns to playlist_mappings

Revision ID: 5510ab9c5136
Revises: 2e3a2758af81
Create Date: 2026-03-09 11:26:07.428640

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5510ab9c5136"
down_revision: str | None = "2e3a2758af81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playlist_mappings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sync_direction",
                sa.String(length=10),
                server_default="push",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "sync_status",
                sa.String(length=20),
                server_default="never_synced",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("last_sync_error", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("last_sync_started_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "last_sync_completed_at", sa.DateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("last_sync_tracks_added", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("last_sync_tracks_removed", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("playlist_mappings", schema=None) as batch_op:
        batch_op.drop_column("last_sync_tracks_removed")
        batch_op.drop_column("last_sync_tracks_added")
        batch_op.drop_column("last_sync_completed_at")
        batch_op.drop_column("last_sync_started_at")
        batch_op.drop_column("last_sync_error")
        batch_op.drop_column("sync_status")
        batch_op.drop_column("sync_direction")

    # ### end Alembic commands ###
