"""add origin to track_mappings

Revision ID: 904c29981ae8
Revises: 5510ab9c5136
Create Date: 2026-03-09 22:42:06.058516

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "904c29981ae8"
down_revision: str | None = "5510ab9c5136"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_mappings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "origin",
                sa.String(length=20),
                server_default="automatic",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("track_mappings", schema=None) as batch_op:
        batch_op.drop_column("origin")

    # ### end Alembic commands ###
