"""add_connector_plays_table

Revision ID: 9c0f10992fa0
Revises: 9265eb69aab8
Create Date: 2025-08-19 22:06:37.485201

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c0f10992fa0"
down_revision: str | None = "9265eb69aab8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_plays",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connector_name", sa.String(length=32), nullable=False),
        sa.Column("connector_track_identifier", sa.String(length=255), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ms_played", sa.Integer(), nullable=True),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("resolved_track_id", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("import_source", sa.String(length=32), nullable=True),
        sa.Column("import_batch_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["resolved_track_id"],
            ["tracks.id"],
            name=op.f("fk_connector_plays_resolved_track_id_tracks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector_plays")),
        sa.UniqueConstraint(
            "connector_name",
            "connector_track_identifier",
            "played_at",
            "ms_played",
            name="uq_connector_plays_deduplication",
        ),
    )
    with op.batch_alter_table("connector_plays", schema=None) as batch_op:
        batch_op.create_index(
            "ix_connector_plays_connector", ["connector_name"], unique=False
        )
        batch_op.create_index(
            "ix_connector_plays_import_batch", ["import_batch_id"], unique=False
        )
        batch_op.create_index(
            "ix_connector_plays_played_at", ["played_at"], unique=False
        )
        batch_op.create_index(
            "ix_connector_plays_resolved_track", ["resolved_track_id"], unique=False
        )
        batch_op.create_index(
            "ix_connector_plays_unresolved",
            ["connector_name", "resolved_track_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connector_plays", schema=None) as batch_op:
        batch_op.drop_index("ix_connector_plays_unresolved")
        batch_op.drop_index("ix_connector_plays_resolved_track")
        batch_op.drop_index("ix_connector_plays_played_at")
        batch_op.drop_index("ix_connector_plays_import_batch")
        batch_op.drop_index("ix_connector_plays_connector")

    op.drop_table("connector_plays")
    # ### end Alembic commands ###
