/**
 * The backend's connector status rule, as data.
 *
 * `derive_status_state()` decides which state a connector card renders, and a
 * test factory that omits `status` has to reproduce it. Hand-mirroring that rule
 * is the drift trap this replaces: the mirror keeps its tests green while the
 * real UI goes wrong. The fixture is generated by `uv run export-status-matrix`
 * (which `pnpm sync-api` runs), and `test_status_matrix_export.py` fails if it
 * falls behind the rule.
 */

import type { ConnectorMetadataSchema } from "#/api/generated/model";

import matrix from "./fixtures/connector-status-matrix.json" with {
  type: "json",
};

type ConnectorStatus = ConnectorMetadataSchema["status"];

export interface StatusMatrixRow {
  auth_method: ConnectorMetadataSchema["auth_method"];
  auth_error: ConnectorMetadataSchema["auth_error"];
  connected: boolean;
  expired: boolean;
  status: ConnectorStatus;
}

/** Every exported row — the contract test's source of cases. */
export const STATUS_MATRIX = matrix as StatusMatrixRow[];

const BY_KEY = new Map<string, ConnectorStatus>(
  STATUS_MATRIX.map((row) => [keyOf(row), row.status]),
);

function keyOf(row: Omit<StatusMatrixRow, "status">): string {
  return [
    row.auth_method,
    row.auth_error ?? "null",
    row.connected,
    row.expired,
  ].join("|");
}

/** Whether an epoch-seconds expiry has passed — the rule's `expired` axis. */
export function expiredAt(tokenExpiresAt: number | null): boolean {
  return tokenExpiresAt !== null && tokenExpiresAt < Date.now() / 1000;
}

/**
 * The state the backend would derive for these inputs.
 *
 * Throws on an unmapped combination rather than defaulting: a new auth method
 * with no exported row is exactly the silent wrong-default the fixture exists to
 * prevent, so it fails loudly at the factory instead of quietly in an assertion.
 */
export function statusStateFor(
  row: Omit<StatusMatrixRow, "status">,
): ConnectorStatus {
  const status = BY_KEY.get(keyOf(row));
  if (status === undefined) {
    throw new Error(
      `No exported status row for ${keyOf(row)} — re-run \`uv run export-status-matrix\`.`,
    );
  }
  return status;
}
